library(dplyr)
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(ggthemes)
library(htmlwidgets)
library(httr)
library(jsonlite)
library(leaflet)
library(leaflet.extras)
library(lubridate)
library(mapview)
library(matlab)
library(RCurl)
library(rtweet)
library(rvest)
library(sf)
library(stringr)
library(tidyverse)
library(utils)
library(withr)
Sys.setenv(PATH = with_path("/projects/covid19/bin", Sys.getenv("PATH")))
curlSetOpt(timeout = 200)